version: "3.9"

services:

  db:
    image: petzen21/postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "cleanDataset"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "cleanDataset", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: petzen21/force_backend:2.0.5
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: "postgresql://admin:admin@db:5432/cleanDataset"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: petzen21/force_frontend:2.0.5
    ports:
      - "8072:8072"
    depends_on:
      - db
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8072"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
